export interface Airport {
  iata: string
  city: string
  name: string
  country: string
}

export const AIRPORTS: Airport[] = [
  // Vietnam
  { iata: 'SGN', city: 'Ho Chi Minh City', name: 'Tan Son Nhat International', country: 'VN' },
  { iata: 'HAN', city: 'Hanoi', name: 'Noi Bai International', country: 'VN' },
  { iata: 'DAD', city: 'Da Nang', name: 'Da Nang International', country: 'VN' },
  { iata: 'CXR', city: 'Nha Trang', name: 'Cam Ranh International', country: 'VN' },
  { iata: 'HPH', city: 'Hai Phong', name: 'Cat Bi International', country: 'VN' },
  { iata: 'VCA', city: 'Can Tho', name: 'Can Tho International', country: 'VN' },
  { iata: 'PQC', city: 'Phu Quoc', name: 'Phu Quoc International', country: 'VN' },
  { iata: 'HUI', city: 'Hue', name: 'Phu Bai International', country: 'VN' },
  { iata: 'DLI', city: 'Da Lat', name: 'Lien Khuong Airport', country: 'VN' },
  { iata: 'UIH', city: 'Qui Nhon', name: 'Phu Cat Airport', country: 'VN' },

  // United States
  { iata: 'ATL', city: 'Atlanta', name: 'Hartsfield-Jackson Atlanta International', country: 'US' },
  { iata: 'LAX', city: 'Los Angeles', name: 'Los Angeles International', country: 'US' },
  { iata: 'ORD', city: 'Chicago', name: "O'Hare International", country: 'US' },
  { iata: 'DFW', city: 'Dallas', name: 'Dallas/Fort Worth International', country: 'US' },
  { iata: 'DEN', city: 'Denver', name: 'Denver International', country: 'US' },
  { iata: 'JFK', city: 'New York', name: 'John F. Kennedy International', country: 'US' },
  { iata: 'SFO', city: 'San Francisco', name: 'San Francisco International', country: 'US' },
  { iata: 'SEA', city: 'Seattle', name: 'Seattle-Tacoma International', country: 'US' },
  { iata: 'LAS', city: 'Las Vegas', name: 'Harry Reid International', country: 'US' },
  { iata: 'MCO', city: 'Orlando', name: 'Orlando International', country: 'US' },
  { iata: 'EWR', city: 'Newark', name: 'Newark Liberty International', country: 'US' },
  { iata: 'MIA', city: 'Miami', name: 'Miami International', country: 'US' },
  { iata: 'PHX', city: 'Phoenix', name: 'Phoenix Sky Harbor International', country: 'US' },
  { iata: 'IAH', city: 'Houston', name: 'George Bush Intercontinental', country: 'US' },
  { iata: 'BOS', city: 'Boston', name: 'Logan International', country: 'US' },
  { iata: 'MSP', city: 'Minneapolis', name: 'Minneapolis-Saint Paul International', country: 'US' },
  { iata: 'DTW', city: 'Detroit', name: 'Detroit Metropolitan Wayne County', country: 'US' },
  { iata: 'FLL', city: 'Fort Lauderdale', name: 'Fort Lauderdale-Hollywood International', country: 'US' },
  { iata: 'PHL', city: 'Philadelphia', name: 'Philadelphia International', country: 'US' },
  { iata: 'LGA', city: 'New York', name: 'LaGuardia Airport', country: 'US' },
  { iata: 'BWI', city: 'Baltimore', name: 'Baltimore/Washington International', country: 'US' },
  { iata: 'IAD', city: 'Washington DC', name: 'Washington Dulles International', country: 'US' },
  { iata: 'DCA', city: 'Washington DC', name: 'Ronald Reagan Washington National', country: 'US' },
  { iata: 'SLC', city: 'Salt Lake City', name: 'Salt Lake City International', country: 'US' },
  { iata: 'SAN', city: 'San Diego', name: 'San Diego International', country: 'US' },
  { iata: 'HNL', city: 'Honolulu', name: 'Daniel K. Inouye International', country: 'US' },
  { iata: 'TPA', city: 'Tampa', name: 'Tampa International', country: 'US' },
  { iata: 'PDX', city: 'Portland', name: 'Portland International', country: 'US' },
  { iata: 'STL', city: 'St. Louis', name: 'St. Louis Lambert International', country: 'US' },
  { iata: 'BNA', city: 'Nashville', name: 'Nashville International', country: 'US' },
  { iata: 'MDW', city: 'Chicago', name: "Chicago Midway International", country: 'US' },
  { iata: 'CLT', city: 'Charlotte', name: 'Charlotte Douglas International', country: 'US' },
  { iata: 'AUS', city: 'Austin', name: 'Austin-Bergstrom International', country: 'US' },
  { iata: 'MSY', city: 'New Orleans', name: 'Louis Armstrong New Orleans International', country: 'US' },
  { iata: 'RDU', city: 'Raleigh', name: 'Raleigh-Durham International', country: 'US' },
  { iata: 'SMF', city: 'Sacramento', name: 'Sacramento International', country: 'US' },
  { iata: 'SJC', city: 'San Jose', name: 'Norman Y. Mineta San Jose International', country: 'US' },
  { iata: 'OAK', city: 'Oakland', name: 'Oakland International', country: 'US' },
  { iata: 'MCI', city: 'Kansas City', name: 'Kansas City International', country: 'US' },
  { iata: 'PIT', city: 'Pittsburgh', name: 'Pittsburgh International', country: 'US' },
  { iata: 'CLE', city: 'Cleveland', name: 'Cleveland Hopkins International', country: 'US' },
  { iata: 'CMH', city: 'Columbus', name: 'John Glenn Columbus International', country: 'US' },
  { iata: 'IND', city: 'Indianapolis', name: 'Indianapolis International', country: 'US' },
  { iata: 'MKE', city: 'Milwaukee', name: 'Milwaukee Mitchell International', country: 'US' },
  { iata: 'OGG', city: 'Maui', name: 'Kahului Airport', country: 'US' },
  { iata: 'BUR', city: 'Burbank', name: 'Hollywood Burbank Airport', country: 'US' },

  // Canada
  { iata: 'YYZ', city: 'Toronto', name: 'Toronto Pearson International', country: 'CA' },
  { iata: 'YVR', city: 'Vancouver', name: 'Vancouver International', country: 'CA' },
  { iata: 'YUL', city: 'Montreal', name: 'Montreal-Trudeau International', country: 'CA' },
  { iata: 'YYC', city: 'Calgary', name: 'Calgary International', country: 'CA' },
  { iata: 'YEG', city: 'Edmonton', name: 'Edmonton International', country: 'CA' },
  { iata: 'YOW', city: 'Ottawa', name: 'Ottawa Macdonald-Cartier International', country: 'CA' },

  // United Kingdom
  { iata: 'LHR', city: 'London', name: 'Heathrow Airport', country: 'GB' },
  { iata: 'LGW', city: 'London', name: 'Gatwick Airport', country: 'GB' },
  { iata: 'STN', city: 'London', name: 'Stansted Airport', country: 'GB' },
  { iata: 'LTN', city: 'London', name: 'Luton Airport', country: 'GB' },
  { iata: 'MAN', city: 'Manchester', name: 'Manchester Airport', country: 'GB' },
  { iata: 'EDI', city: 'Edinburgh', name: 'Edinburgh Airport', country: 'GB' },
  { iata: 'BHX', city: 'Birmingham', name: 'Birmingham Airport', country: 'GB' },
  { iata: 'GLA', city: 'Glasgow', name: 'Glasgow Airport', country: 'GB' },

  // Europe
  { iata: 'CDG', city: 'Paris', name: 'Charles de Gaulle Airport', country: 'FR' },
  { iata: 'ORY', city: 'Paris', name: 'Orly Airport', country: 'FR' },
  { iata: 'NCE', city: 'Nice', name: 'Nice Côte d\'Azur Airport', country: 'FR' },
  { iata: 'FRA', city: 'Frankfurt', name: 'Frankfurt Airport', country: 'DE' },
  { iata: 'MUC', city: 'Munich', name: 'Munich Airport', country: 'DE' },
  { iata: 'TXL', city: 'Berlin', name: 'Berlin Tegel Airport', country: 'DE' },
  { iata: 'BER', city: 'Berlin', name: 'Berlin Brandenburg Airport', country: 'DE' },
  { iata: 'HAM', city: 'Hamburg', name: 'Hamburg Airport', country: 'DE' },
  { iata: 'AMS', city: 'Amsterdam', name: 'Amsterdam Schiphol Airport', country: 'NL' },
  { iata: 'MAD', city: 'Madrid', name: 'Adolfo Suárez Madrid-Barajas Airport', country: 'ES' },
  { iata: 'BCN', city: 'Barcelona', name: 'Barcelona El Prat Airport', country: 'ES' },
  { iata: 'FCO', city: 'Rome', name: 'Leonardo da Vinci International', country: 'IT' },
  { iata: 'MXP', city: 'Milan', name: 'Malpensa Airport', country: 'IT' },
  { iata: 'LIN', city: 'Milan', name: 'Linate Airport', country: 'IT' },
  { iata: 'VCE', city: 'Venice', name: 'Venice Marco Polo Airport', country: 'IT' },
  { iata: 'ZRH', city: 'Zurich', name: 'Zurich Airport', country: 'CH' },
  { iata: 'GVA', city: 'Geneva', name: 'Geneva Airport', country: 'CH' },
  { iata: 'VIE', city: 'Vienna', name: 'Vienna International Airport', country: 'AT' },
  { iata: 'BRU', city: 'Brussels', name: 'Brussels Airport', country: 'BE' },
  { iata: 'CPH', city: 'Copenhagen', name: 'Copenhagen Airport', country: 'DK' },
  { iata: 'ARN', city: 'Stockholm', name: 'Stockholm Arlanda Airport', country: 'SE' },
  { iata: 'OSL', city: 'Oslo', name: 'Oslo Gardermoen Airport', country: 'NO' },
  { iata: 'HEL', city: 'Helsinki', name: 'Helsinki-Vantaa Airport', country: 'FI' },
  { iata: 'LIS', city: 'Lisbon', name: 'Lisbon Portela Airport', country: 'PT' },
  { iata: 'OPO', city: 'Porto', name: 'Francisco Sá Carneiro Airport', country: 'PT' },
  { iata: 'ATH', city: 'Athens', name: 'Athens International Airport', country: 'GR' },
  { iata: 'WAW', city: 'Warsaw', name: 'Warsaw Chopin Airport', country: 'PL' },
  { iata: 'PRG', city: 'Prague', name: 'Václav Havel Airport Prague', country: 'CZ' },
  { iata: 'BUD', city: 'Budapest', name: 'Budapest Ferenc Liszt International', country: 'HU' },
  { iata: 'DUB', city: 'Dublin', name: 'Dublin Airport', country: 'IE' },
  { iata: 'IST', city: 'Istanbul', name: 'Istanbul Airport', country: 'TR' },
  { iata: 'SAW', city: 'Istanbul', name: 'Sabiha Gökçen International', country: 'TR' },
  { iata: 'ESB', city: 'Ankara', name: 'Esenboğa International Airport', country: 'TR' },

  // Middle East
  { iata: 'DXB', city: 'Dubai', name: 'Dubai International Airport', country: 'AE' },
  { iata: 'AUH', city: 'Abu Dhabi', name: 'Abu Dhabi International Airport', country: 'AE' },
  { iata: 'DOH', city: 'Doha', name: 'Hamad International Airport', country: 'QA' },
  { iata: 'RUH', city: 'Riyadh', name: 'King Khalid International Airport', country: 'SA' },
  { iata: 'JED', city: 'Jeddah', name: 'King Abdulaziz International Airport', country: 'SA' },
  { iata: 'KWI', city: 'Kuwait City', name: 'Kuwait International Airport', country: 'KW' },
  { iata: 'BAH', city: 'Manama', name: 'Bahrain International Airport', country: 'BH' },
  { iata: 'MCT', city: 'Muscat', name: 'Muscat International Airport', country: 'OM' },
  { iata: 'AMM', city: 'Amman', name: 'Queen Alia International Airport', country: 'JO' },
  { iata: 'BEY', city: 'Beirut', name: 'Beirut Rafic Hariri International Airport', country: 'LB' },
  { iata: 'TLV', city: 'Tel Aviv', name: 'Ben Gurion International Airport', country: 'IL' },

  // East Asia
  { iata: 'NRT', city: 'Tokyo', name: 'Narita International Airport', country: 'JP' },
  { iata: 'HND', city: 'Tokyo', name: 'Haneda Airport', country: 'JP' },
  { iata: 'KIX', city: 'Osaka', name: 'Kansai International Airport', country: 'JP' },
  { iata: 'NGO', city: 'Nagoya', name: 'Chubu Centrair International Airport', country: 'JP' },
  { iata: 'CTS', city: 'Sapporo', name: 'New Chitose Airport', country: 'JP' },
  { iata: 'FUK', city: 'Fukuoka', name: 'Fukuoka Airport', country: 'JP' },
  { iata: 'ICN', city: 'Seoul', name: 'Incheon International Airport', country: 'KR' },
  { iata: 'GMP', city: 'Seoul', name: 'Gimpo International Airport', country: 'KR' },
  { iata: 'PUS', city: 'Busan', name: 'Gimhae International Airport', country: 'KR' },
  { iata: 'PEK', city: 'Beijing', name: 'Beijing Capital International Airport', country: 'CN' },
  { iata: 'PKX', city: 'Beijing', name: 'Beijing Daxing International Airport', country: 'CN' },
  { iata: 'PVG', city: 'Shanghai', name: 'Shanghai Pudong International Airport', country: 'CN' },
  { iata: 'SHA', city: 'Shanghai', name: 'Shanghai Hongqiao International Airport', country: 'CN' },
  { iata: 'CAN', city: 'Guangzhou', name: 'Guangzhou Baiyun International Airport', country: 'CN' },
  { iata: 'SZX', city: 'Shenzhen', name: 'Shenzhen Bao\'an International Airport', country: 'CN' },
  { iata: 'CTU', city: 'Chengdu', name: 'Chengdu Tianfu International Airport', country: 'CN' },
  { iata: 'HKG', city: 'Hong Kong', name: 'Hong Kong International Airport', country: 'HK' },
  { iata: 'TPE', city: 'Taipei', name: 'Taiwan Taoyuan International Airport', country: 'TW' },
  { iata: 'TSA', city: 'Taipei', name: 'Taipei Songshan Airport', country: 'TW' },
  { iata: 'MFM', city: 'Macau', name: 'Macau International Airport', country: 'MO' },

  // Southeast Asia
  { iata: 'SIN', city: 'Singapore', name: 'Singapore Changi Airport', country: 'SG' },
  { iata: 'BKK', city: 'Bangkok', name: 'Suvarnabhumi Airport', country: 'TH' },
  { iata: 'DMK', city: 'Bangkok', name: 'Don Mueang International Airport', country: 'TH' },
  { iata: 'HKT', city: 'Phuket', name: 'Phuket International Airport', country: 'TH' },
  { iata: 'CNX', city: 'Chiang Mai', name: 'Chiang Mai International Airport', country: 'TH' },
  { iata: 'KUL', city: 'Kuala Lumpur', name: 'Kuala Lumpur International Airport', country: 'MY' },
  { iata: 'JHB', city: 'Johor Bahru', name: 'Senai International Airport', country: 'MY' },
  { iata: 'CGK', city: 'Jakarta', name: 'Soekarno-Hatta International Airport', country: 'ID' },
  { iata: 'DPS', city: 'Bali', name: 'Ngurah Rai International Airport', country: 'ID' },
  { iata: 'SUB', city: 'Surabaya', name: 'Juanda International Airport', country: 'ID' },
  { iata: 'MNL', city: 'Manila', name: 'Ninoy Aquino International Airport', country: 'PH' },
  { iata: 'CEB', city: 'Cebu', name: 'Mactan-Cebu International Airport', country: 'PH' },
  { iata: 'RGN', city: 'Yangon', name: 'Yangon International Airport', country: 'MM' },
  { iata: 'REP', city: 'Siem Reap', name: 'Siem Reap International Airport', country: 'KH' },
  { iata: 'PNH', city: 'Phnom Penh', name: 'Phnom Penh International Airport', country: 'KH' },
  { iata: 'VTE', city: 'Vientiane', name: 'Wattay International Airport', country: 'LA' },

  // South Asia
  { iata: 'DEL', city: 'Delhi', name: 'Indira Gandhi International Airport', country: 'IN' },
  { iata: 'BOM', city: 'Mumbai', name: 'Chhatrapati Shivaji Maharaj International', country: 'IN' },
  { iata: 'BLR', city: 'Bengaluru', name: 'Kempegowda International Airport', country: 'IN' },
  { iata: 'MAA', city: 'Chennai', name: 'Chennai International Airport', country: 'IN' },
  { iata: 'CCU', city: 'Kolkata', name: 'Netaji Subhas Chandra Bose International', country: 'IN' },
  { iata: 'HYD', city: 'Hyderabad', name: 'Rajiv Gandhi International Airport', country: 'IN' },
  { iata: 'CMB', city: 'Colombo', name: 'Bandaranaike International Airport', country: 'LK' },
  { iata: 'DAC', city: 'Dhaka', name: 'Hazrat Shahjalal International Airport', country: 'BD' },
  { iata: 'KTM', city: 'Kathmandu', name: 'Tribhuvan International Airport', country: 'NP' },

  // Australia & Pacific
  { iata: 'SYD', city: 'Sydney', name: 'Sydney Kingsford Smith Airport', country: 'AU' },
  { iata: 'MEL', city: 'Melbourne', name: 'Melbourne Airport', country: 'AU' },
  { iata: 'BNE', city: 'Brisbane', name: 'Brisbane Airport', country: 'AU' },
  { iata: 'PER', city: 'Perth', name: 'Perth Airport', country: 'AU' },
  { iata: 'ADL', city: 'Adelaide', name: 'Adelaide Airport', country: 'AU' },
  { iata: 'AKL', city: 'Auckland', name: 'Auckland Airport', country: 'NZ' },
  { iata: 'CHC', city: 'Christchurch', name: 'Christchurch Airport', country: 'NZ' },
  { iata: 'NAN', city: 'Nadi', name: 'Nadi International Airport', country: 'FJ' },

  // Africa
  { iata: 'JNB', city: 'Johannesburg', name: 'O.R. Tambo International Airport', country: 'ZA' },
  { iata: 'CPT', city: 'Cape Town', name: 'Cape Town International Airport', country: 'ZA' },
  { iata: 'DUR', city: 'Durban', name: 'King Shaka International Airport', country: 'ZA' },
  { iata: 'CAI', city: 'Cairo', name: 'Cairo International Airport', country: 'EG' },
  { iata: 'HRG', city: 'Hurghada', name: 'Hurghada International Airport', country: 'EG' },
  { iata: 'SSH', city: 'Sharm el-Sheikh', name: 'Sharm el-Sheikh International Airport', country: 'EG' },
  { iata: 'ADD', city: 'Addis Ababa', name: 'Addis Ababa Bole International Airport', country: 'ET' },
  { iata: 'NBO', city: 'Nairobi', name: 'Jomo Kenyatta International Airport', country: 'KE' },
  { iata: 'CMN', city: 'Casablanca', name: 'Mohammed V International Airport', country: 'MA' },
  { iata: 'TUN', city: 'Tunis', name: 'Tunis-Carthage International Airport', country: 'TN' },
  { iata: 'LOS', city: 'Lagos', name: 'Murtala Muhammed International Airport', country: 'NG' },
  { iata: 'ABV', city: 'Abuja', name: 'Nnamdi Azikiwe International Airport', country: 'NG' },
  { iata: 'ACC', city: 'Accra', name: 'Kotoka International Airport', country: 'GH' },
  { iata: 'DAR', city: 'Dar es Salaam', name: 'Julius Nyerere International Airport', country: 'TZ' },

  // Latin America
  { iata: 'GRU', city: 'São Paulo', name: 'São Paulo/Guarulhos International Airport', country: 'BR' },
  { iata: 'GIG', city: 'Rio de Janeiro', name: 'Rio de Janeiro/Galeão International Airport', country: 'BR' },
  { iata: 'BSB', city: 'Brasília', name: 'Brasília International Airport', country: 'BR' },
  { iata: 'EZE', city: 'Buenos Aires', name: 'Ministro Pistarini International Airport', country: 'AR' },
  { iata: 'AEP', city: 'Buenos Aires', name: 'Jorge Newbery Airfield', country: 'AR' },
  { iata: 'SCL', city: 'Santiago', name: 'Arturo Merino Benítez International Airport', country: 'CL' },
  { iata: 'BOG', city: 'Bogotá', name: 'El Dorado International Airport', country: 'CO' },
  { iata: 'LIM', city: 'Lima', name: 'Jorge Chávez International Airport', country: 'PE' },
  { iata: 'UIO', city: 'Quito', name: 'Mariscal Sucre International Airport', country: 'EC' },
  { iata: 'GYE', city: 'Guayaquil', name: 'José Joaquín de Olmedo International Airport', country: 'EC' },
  { iata: 'CCS', city: 'Caracas', name: 'Simón Bolívar International Airport', country: 'VE' },
  { iata: 'MEX', city: 'Mexico City', name: 'Benito Juárez International Airport', country: 'MX' },
  { iata: 'CUN', city: 'Cancún', name: 'Cancún International Airport', country: 'MX' },
  { iata: 'GDL', city: 'Guadalajara', name: 'Miguel Hidalgo y Costilla International Airport', country: 'MX' },
  { iata: 'MTY', city: 'Monterrey', name: 'General Mariano Escobedo International Airport', country: 'MX' },
  { iata: 'SJO', city: 'San José', name: 'Juan Santamaría International Airport', country: 'CR' },
  { iata: 'PTY', city: 'Panama City', name: 'Tocumen International Airport', country: 'PA' },

  // Russia & Central Asia
  { iata: 'SVO', city: 'Moscow', name: 'Sheremetyevo International Airport', country: 'RU' },
  { iata: 'DME', city: 'Moscow', name: 'Domodedovo International Airport', country: 'RU' },
  { iata: 'LED', city: 'St. Petersburg', name: 'Pulkovo Airport', country: 'RU' },
  { iata: 'ALA', city: 'Almaty', name: 'Almaty International Airport', country: 'KZ' },
  { iata: 'TAS', city: 'Tashkent', name: 'Islam Karimov Tashkent International Airport', country: 'UZ' },
]

export function searchAirports(query: string, limit = 8): Airport[] {
  const q = query.trim().toUpperCase()
  if (!q) return []
  return AIRPORTS.filter(a =>
    a.iata.startsWith(q) ||
    a.city.toUpperCase().includes(q) ||
    a.name.toUpperCase().includes(q)
  ).slice(0, limit)
}
